name: Main

on:
  push:
    branches: [ main, dev ]
  pull_request: 
    branches: [ main, dev ]

jobs:
  style:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Style Check
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "."
          use-pylint: false
          use-pycodestyle: true
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: true
          extra-pylint-options: ""
          extra-pycodestyle-options: "--config=./.pycodestyle"
          extra-flake8-options: ""
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: "--profile black"
